# Generated by Django 4.0.6 on 2022-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=55)),
                ('desc', models.TextField(max_length=66)),
                ('year', models.IntegerField(verbose_name=())),
            ],
        ),
    ]
